apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    helm:
      values: |
        prometheus:
          enabled: true
          podmonitor:
            enabled: true
        installCRDs: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true

    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
