apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-v2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: coder
  project: default
  source:
    helm:
      values:  |
        coder:
          # You can specify any environment variables you'd like to pass to Coder
          # here. Coder consumes environment variables listed in
          # `coder server --help`, and these environment variables are also passed
          # to the workspace provisioner (so you can consume them in your Terraform
          # templates for auth keys etc.).
          #
          # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
          # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
          # they are already set by the Helm chart and will cause conflicts.
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  # You'll need to create a secret called coder-db-url with your
                  # Postgres connection URL like:
                  # postgres://coder:password@postgres:5432/coder?sslmode=disable
                  name: coder-db-url
                  key: url
            # For production deployments, we recommend configuring your own GitHub
            # OAuth2 provider and disabling the default one.
            #- name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
            #  value: "false"

            # (Optional) For production deployments the access URL should be set.
            # If you're just trying Coder, access the dashboard via the service IP.
            - name: CODER_ACCESS_URL
              value: "https://coder.kylebrighton.com"

            - name: CODER_WILDCARD_ACCESS_URL
              value: "*.coder.kylebrighton.com"
            - name: CODER_HTTP_ACCESS
              value: "192.168.0.4"
            - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
              value: "true"
            - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
              value: "nexuslarptools"
            - name: CODER_OAUTH2_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: CODER_OAUTH2_GITHUB_CLIENT_ID

            - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: CODER_OAUTH2_GITHUB_CLIENT_SECRET

            #tls:
            #  secretNames:
            #    - my-tls-secret-name
    repoURL: https://helm.coder.com/v2
    chart: coder
    targetRevision: 2.23.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
