apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-adguard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns-adguard
  project: default
  source:
    helm:
      values:  |
        domainFilters: ["int.kylebrighton.com"]
        provider: rfc2136
        extraArgs:
          - --rfc2136-host=192.168.1.176
          - --rfc2136-port=53
          - --rfc2136-zone=int.kylebrighton.com
          - --rfc2136-tsig-secret-alg=hmac-sha256
          - --rfc2136-tsig-keyname=external-dns
          - --rfc2136-tsig-axfr

        env:
          - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
            valueFrom:
              secretKeyRef:
                name: tsig-key
                key: key
        gatewayNamespace: traefik
        sources:
        - service
        - ingress
        - gateway-httproute
        policy: sync

    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.20.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
