apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphoreui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  project: default
  source:
    helm:
      values:  |
        ingress:
          annotations:
            external-dns.alpha.kubernetes.io/target: "7c6ce3b1-97d9-4ac3-aefa-516c85871114.cfargotunnel.com"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          enabled: true
          hosts:
            - host: semaphore.kylebrighton.com
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: synostorage
        database:
          persistence:
            storageClass: synostorage
        service:
          type: LoadBalancer

    repoURL: https://semaphoreui.github.io/charts
    chart: semaphore
    targetRevision: 16.0.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
