argo-cd:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    enabled: false
  repoServer:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  redis:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  server:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: LoadBalancer
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
