argo-cd:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  dex:
    enabled: false
  server:
    service:
      type: LoadBalancer
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
